# Generated by Django 5.2.8 on 2025-11-27 14:56

import cadastro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('local_nascimento', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cns', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cartão Nacional de Saúde')),
                ('sis', models.CharField(blank=True, max_length=20, null=True)),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('cid', models.CharField(choices=[('F84.0', 'F84.0 - Autismo Infantil'), ('F84.1', 'F84.1 - Autismo Atípico'), ('F84.5', 'F84.5 - Síndrome de Asperger'), ('F84.9', 'F84.9 - Transtorno global do desenvolvimento SOE')], max_length=10)),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(upload_to=cadastro.models.get_file_path, verbose_name='Foto 3x4')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('perfil', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('TUTOR', 'Tutor Legal'), ('OUTRO', 'Outro')], max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('beneficiario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='cadastro.beneficiario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ANALISE', 'Em Análise'), ('PENDENTE', 'Pendência de Documento'), ('APROVADO', 'Aprovado'), ('IMPRESSO', 'Impresso/Entregue'), ('REJEITADO', 'Rejeitado')], default='ABERTO', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('analista_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=cadastro.models.get_file_path)),
                ('tipo', models.CharField(choices=[('LAUDO', 'Laudo Médico'), ('RG_BENEF', 'RG do Beneficiário'), ('RG_RESP', 'RG do Responsável'), ('COMP_RES', 'Comprovante de Residência'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('aprovado', models.BooleanField(default=False)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='cadastro.solicitacao')),
            ],
        ),
    ]
