# Generated by Django 5.2.8 on 2025-11-28 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(default='Sistema', max_length=100)),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('ANALISE', 'Análise'), ('PENDENCIA', 'Pendência'), ('CONCLUSAO', 'Conclusão')], default='ANALISE', max_length=20)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cadastro.solicitacao')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
