# Generated by Django 5.2.8 on 2025-11-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='motivo_rejeicao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
