# Generated by Django 5.2.8 on 2025-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_documento_motivo_rejeicao_documento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='perfil',
            field=models.CharField(choices=[('MAE', 'Mãe'), ('PAI', 'Pai'), ('AVO', 'Avô/Avó'), ('TIO', 'Tio/Tia'), ('TUTOR', 'Tutor/Curador'), ('PROPRIO', 'Próprio Beneficiário'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
