# Generated by Django 5.2.8 on 2025-12-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_responsavel_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='cadastro.beneficiario'),
        ),
    ]
