# Generated by Django 5.2.8 on 2025-12-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_responsavel_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='motivo_rejeicao_foto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='status_foto',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
    ]
