# Generated by Django 5.2.8 on 2025-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_beneficiario_motivo_rejeicao_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANALISE', 'Em Análise'), ('PENDENTE', 'Pendência de Documento'), ('APROVADO', 'Aprovado'), ('IMPRESSO', 'Impresso/Entregue'), ('INDEFERIDO', 'Indeferido')], default='ABERTO', max_length=20),
        ),
    ]
