# Generated by Django 5.2.8 on 2025-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='origem',
            field=models.CharField(choices=[('SISTEMA_NOVO', 'Sistema Novo (Digital)'), ('LEGADO', 'Sistema Antigo (Importado)')], default='SISTEMA_NOVO', max_length=20),
        ),
    ]
