# Generated by Django 5.2.8 on 2025-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_solicitacao_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('LEGADO', 'Sistema Antigo (Aguardando Atualização)'), ('ABERTO', 'Aberto'), ('ANALISE', 'Em Análise'), ('PENDENTE', 'Pendência de Documento'), ('APROVADO', 'Aprovado'), ('IMPRESSO', 'Impresso/Entregue'), ('INDEFERIDO', 'Indeferido')], default='ABERTO', max_length=20),
        ),
    ]
