# Generated by Django 5.2.8 on 2026-04-27 19:32

import django.db.models.deletion
from django.db import migrations, models


def add_validade_anos_if_missing(apps, schema_editor):
    Solicitacao = apps.get_model('cadastro', 'Solicitacao')
    table_name = Solicitacao._meta.db_table
    existing_columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table_name
        )
    }
    if 'validade_anos' in existing_columns:
        return
    field = models.PositiveSmallIntegerField(default=5)
    field.set_attributes_from_name('validade_anos')
    schema_editor.add_field(Solicitacao, field)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='primeira_digitalizacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='renovacao_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovacoes', to='cadastro.solicitacao'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='tipo_fluxo',
            field=models.CharField(choices=[('PRIMEIRA_VIA', 'Primeira via'), ('RENOVACAO', 'Renovação')], default='PRIMEIRA_VIA', max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_validade_anos_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='solicitacao',
                    name='validade_anos',
                    field=models.PositiveSmallIntegerField(default=5),
                ),
            ],
        ),
    ]
