# Generated by Django 5.2.8 on 2026-04-27 20:24

import cadastro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_solicitacao_primeira_digitalizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidacaoDocumentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_laudo_medico', models.FileField(blank=True, null=True, upload_to=cadastro.models.get_file_path)),
                ('arquivo_doc_tea', models.FileField(blank=True, null=True, upload_to=cadastro.models.get_file_path)),
                ('arquivo_doc_responsavel', models.FileField(blank=True, null=True, upload_to=cadastro.models.get_file_path)),
                ('arquivo_comprovante_endereco', models.FileField(blank=True, null=True, upload_to=cadastro.models.get_file_path)),
                ('status_validacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO_IA', 'Aprovado pela IA'), ('REVISAO_MANUAL', 'Revisão Manual')], default='PENDENTE', max_length=20)),
                ('log_ia', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validacao_ia', to='cadastro.solicitacao')),
            ],
        ),
    ]
