# Generated by Django 5.2.8 on 2026-05-06 19:48

import cadastro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_validacaodocumentoia'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='documento_identidade',
            field=models.FileField(blank=True, help_text='Upload do RG ou CNH do Responsável', null=True, upload_to=cadastro.models.get_file_path),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='motivo_rejeicao_documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='status_documento',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('LAUDO', 'Laudo Médico'), ('RG_BENEF', 'RG do Beneficiário'), ('COMP_RES', 'Comprovante de Residência'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
